import { Device, User } from "./types";

export const users: User[] = [
  { id: 1, username: 'adminuser', password: 'password123', role: 'admin' },
  { id: 2, username: 'opuser', password: 'password456', role: 'operator' },
  { id: 3, username: 'viewer1', password: 'viewerpass1', role: 'operator' },
  { id: 4, username: 'viewer2', password: 'viewerpass2', role: 'operator' },
  { id: 5, username: 'manager1', password: '', role: 'admin' },
  { id: 6, username: 'manager2', password: 'managerpass2', role: 'admin' },
];

export const devices: Device[] = [
  {
    id: '1',
    temperature: '23 c',
    humidity: '90%',
    lat: 25.243143,
    lng: 55.326633,
    name: 'sensor-1',
    status: 'on',
    totalPowerConsumption: {
      jan: '24 kw',
      feb: '21 kw',
      march: '22 kw',
      april: '28 kw',
      may: '29 kw',
      june: '31 kw',
      july: '34 kw',
      august: '23 kw',
      september: '44 kw',
      october: '41 kw',
      november: '24 kw',
      december: '21 kw',
    },
  },
  {
    id: '2',
    temperature: '21 c',
    humidity: '92%',
    lat: 25.12235,
    lng: 55.37482,
    name: 'sensor-2',
    status: 'off',
    totalPowerConsumption: {
      jan: '22 kw',
      feb: '20 kw',
      march: '23 kw',
      april: '25 kw',
      may: '26 kw',
      june: '27 kw',
      july: '28 kw',
      august: '22 kw',
      september: '30 kw',
      october: '29 kw',
      november: '21 kw',
      december: '20 kw',
    },
  },
  {
    id: '3',
    temperature: '25 c',
    humidity: '88%',
    lat: 25.2048,
    lng: 55.2708,
    name: 'sensor-3-downtown',
    status: 'on',
    totalPowerConsumption: {
      jan: '30 kw',
      feb: '28 kw',
      march: '29 kw',
      april: '31 kw',
      may: '32 kw',
      june: '33 kw',
      july: '34 kw',
      august: '30 kw',
      september: '35 kw',
      october: '36 kw',
      november: '29 kw',
      december: '28 kw',
    },
  },
  {
    id: '4',
    temperature: '22 c',
    humidity: '91%',
    lat: 25.0779,
    lng: 55.1390,
    name: 'sensor-4-marina',
    status: 'on',
    totalPowerConsumption: {
      jan: '28 kw',
      feb: '27 kw',
      march: '26 kw',
      april: '29 kw',
      may: '30 kw',
      june: '31 kw',
      july: '32 kw',
      august: '28 kw',
      september: '33 kw',
      october: '34 kw',
      november: '27 kw',
      december: '26 kw',
    },
  },
  {
    id: '5',
    temperature: '24 c',
    humidity: '85%',
    lat: 25.276987,
    lng: 55.296249,
    name: 'sensor-5-deira',
    status: 'off',
    totalPowerConsumption: {
      jan: '25 kw',
      feb: '24 kw',
      march: '23 kw',
      april: '26 kw',
      may: '27 kw',
      june: '28 kw',
      july: '29 kw',
      august: '25 kw',
      september: '30 kw',
      october: '31 kw',
      november: '24 kw',
      december: '23 kw',
    },
  },
  {
    id: '6',
    temperature: '26 c',
    humidity: '89%',
    lat: 25.1972,
    lng: 55.2744,
    name: 'sensor-6-businessbay',
    status: 'on',
    totalPowerConsumption: {
      jan: '35 kw',
      feb: '34 kw',
      march: '33 kw',
      april: '36 kw',
      may: '37 kw',
      june: '38 kw',
      july: '39 kw',
      august: '35 kw',
      september: '40 kw',
      october: '41 kw',
      november: '34 kw',
      december: '33 kw',
    },
  },
  {
    id: '7',
    temperature: '20 c',
    humidity: '95%',
    lat: 25.0963,
    lng: 55.1498,
    name: 'sensor-7-jlt',
    status: 'on',
    totalPowerConsumption: {
      jan: '20 kw',
      feb: '19 kw',
      march: '18 kw',
      april: '21 kw',
      may: '22 kw',
      june: '23 kw',
      july: '24 kw',
      august: '20 kw',
      september: '25 kw',
      october: '26 kw',
      november: '19 kw',
      december: '18 kw',
    },
  },
  {
    id: '8',
    temperature: '27 c',
    humidity: '80%',
    lat: 25.2582,
    lng: 55.3047,
    name: 'sensor-8-karama',
    status: 'on',
    totalPowerConsumption: {
      jan: '40 kw',
      feb: '39 kw',
      march: '38 kw',
      april: '41 kw',
      may: '42 kw',
      june: '43 kw',
      july: '44 kw',
      august: '40 kw',
      september: '45 kw',
      october: '46 kw',
      november: '39 kw',
      december: '38 kw',
    },
  },
  {
    id: '9',
    temperature: '23 c',
    humidity: '93%',
    lat: 25.1193,
    lng: 55.2048,
    name: 'sensor-9-albarsha',
    status: 'off',
    totalPowerConsumption: {
      jan: '26 kw',
      feb: '25 kw',
      march: '24 kw',
      april: '27 kw',
      may: '28 kw',
      june: '29 kw',
      july: '30 kw',
      august: '26 kw',
      september: '31 kw',
      october: '32 kw',
      november: '25 kw',
      december: '24 kw',
    },
  },
  {
    id: '10',
    temperature: '24 c',
    humidity: '87%',
    lat: 25.2285,
    lng: 55.3100,
    name: 'sensor-10-oudmetha',
    status: 'on',
    totalPowerConsumption: {
      jan: '31 kw',
      feb: '30 kw',
      march: '29 kw',
      april: '32 kw',
      may: '33 kw',
      june: '34 kw',
      july: '35 kw',
      august: '31 kw',
      september: '36 kw',
      october: '37 kw',
      november: '30 kw',
      december: '29 kw',
    },
  },
];